# Generated by Django 6.0.1 on 2026-01-12 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อสินค้า')),
                ('cost', models.FloatField(verbose_name='ราคาต้นทุน')),
                ('stock', models.IntegerField(default=0, verbose_name='จำนวนคงเหลือ')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_given', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.item')),
            ],
        ),
    ]
